import { Category, Contact } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'police',
    name: 'Police & Security',
    icon: 'Shield',
    description: 'Thana, SP Office, and Outposts',
    color: 'bg-blue-600 hover:bg-blue-700 text-white',
    borderColor: 'border-blue-200',
    bgLight: 'bg-blue-50',
  },
  {
    id: 'fire_service',
    name: 'Fire Service',
    icon: 'Flame',
    description: 'Emergency fire fighting & rescue',
    color: 'bg-red-600 hover:bg-red-700 text-white',
    borderColor: 'border-red-200',
    bgLight: 'bg-red-50',
  },
  {
    id: 'ambulance',
    name: 'Ambulance Services',
    icon: 'Ambulance',
    description: '24/7 emergency patient transport',
    color: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    borderColor: 'border-emerald-200',
    bgLight: 'bg-emerald-50',
  },
  {
    id: 'hospitals',
    name: 'Hospitals & Doctors',
    icon: 'HeartPulse',
    description: 'Upazila health complexes and chambers',
    color: 'bg-indigo-600 hover:bg-indigo-700 text-white',
    borderColor: 'border-indigo-200',
    bgLight: 'bg-indigo-50',
  },
  {
    id: 'blood_donors',
    name: 'Blood Donors',
    icon: 'Droplet',
    description: 'Volunteers and blood bank groups',
    color: 'bg-rose-600 hover:bg-rose-700 text-white',
    borderColor: 'border-rose-200',
    bgLight: 'bg-rose-50',
  },
  {
    id: 'pharmacies',
    name: '24/7 Pharmacies',
    icon: 'Pill',
    description: 'Medicine stores with night shifts',
    color: 'bg-teal-600 hover:bg-teal-700 text-white',
    borderColor: 'border-teal-200',
    bgLight: 'bg-teal-50',
  },
  {
    id: 'transportation',
    name: 'Transportation',
    icon: 'Bus',
    description: 'Bus counters, launch & rent-a-car',
    color: 'bg-amber-600 hover:bg-amber-700 text-white',
    borderColor: 'border-amber-200',
    bgLight: 'bg-amber-50',
  },
  {
    id: 'gov_offices',
    name: 'Govt & Electricity',
    icon: 'Building',
    description: 'Palli Bidyut, Union Parishad, etc.',
    color: 'bg-slate-700 hover:bg-slate-800 text-white',
    borderColor: 'border-slate-200',
    bgLight: 'bg-slate-50',
  },
  {
    id: 'hotlines',
    name: 'National Emergency Hotlines',
    icon: 'PhoneCall',
    description: '999, 333, 109, 1098 & toll-free helplines',
    color: 'bg-rose-700 hover:bg-rose-800 text-white',
    borderColor: 'border-rose-200',
    bgLight: 'bg-rose-50',
  },
  {
    id: 'education',
    name: 'Education & Colleges',
    icon: 'GraduationCap',
    description: 'Govt. colleges, schools, polytechnic & institutes',
    color: 'bg-cyan-600 hover:bg-cyan-700 text-white',
    borderColor: 'border-cyan-200',
    bgLight: 'bg-cyan-50',
  },
  {
    id: 'banks',
    name: 'Banks & ATM Booths',
    icon: 'Landmark',
    description: 'Sonali, Islami, DBBL, agent banking & ATMs',
    color: 'bg-emerald-700 hover:bg-emerald-800 text-white',
    borderColor: 'border-emerald-200',
    bgLight: 'bg-emerald-50',
  },
  {
    id: 'legal_help',
    name: 'Legal Aid & Lawyers',
    icon: 'Scale',
    description: 'District bar association, legal aid & advocates',
    color: 'bg-amber-700 hover:bg-amber-800 text-white',
    borderColor: 'border-amber-200',
    bgLight: 'bg-amber-50',
  },
  {
    id: 'journalists',
    name: 'Journalists & Press Club',
    icon: 'Newspaper',
    description: 'Shariatpur Press Club & TV correspondents',
    color: 'bg-purple-600 hover:bg-purple-700 text-white',
    borderColor: 'border-purple-200',
    bgLight: 'bg-purple-50',
  },
  {
    id: 'hotels_tourism',
    name: 'Hotels & Tourism',
    icon: 'Compass',
    description: 'Padma Bridge tourism, rest houses & hotels',
    color: 'bg-orange-600 hover:bg-orange-700 text-white',
    borderColor: 'border-orange-200',
    bgLight: 'bg-orange-50',
  },
  {
    id: 'agriculture',
    name: 'Agriculture & Livestock',
    icon: 'Sprout',
    description: 'Upazila agriculture, veterinary & crop helpline',
    color: 'bg-lime-700 hover:bg-lime-800 text-white',
    borderColor: 'border-lime-200',
    bgLight: 'bg-lime-50',
  },
  {
    id: 'union_parishad',
    name: 'Union & Digital Centers',
    icon: 'Landmark',
    description: 'Union Parishad, NID, birth registration & civic services',
    color: 'bg-teal-700 hover:bg-teal-800 text-white',
    borderColor: 'border-teal-200',
    bgLight: 'bg-teal-50',
  },
  {
    id: 'passport_land',
    name: 'Passport, NID & Land Services',
    icon: 'FileText',
    description: 'District passport office, AC Land & Sub-registry',
    color: 'bg-blue-700 hover:bg-blue-800 text-white',
    borderColor: 'border-blue-200',
    bgLight: 'bg-blue-50',
  },
  {
    id: 'home_nursing',
    name: 'Home Nursing & Oxygen',
    icon: 'Stethoscope',
    description: 'Home nurse caregivers, oxygen cylinder & physiotherapy',
    color: 'bg-rose-700 hover:bg-rose-800 text-white',
    borderColor: 'border-rose-200',
    bgLight: 'bg-rose-50',
  },
  {
    id: 'courier',
    name: 'Courier & Parcel Services',
    icon: 'Truck',
    description: 'Sundarban, SA Paribahan, Steadfast & RedX courier',
    color: 'bg-amber-600 hover:bg-amber-700 text-white',
    borderColor: 'border-amber-200',
    bgLight: 'bg-amber-50',
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  // === POLICE ===
  {
    id: 'p1',
    name: 'Shariatpur District SP Office',
    category: 'police',
    phoneNumber: '+8801320108300',
    upazila: 'Sadar',
    location: 'Sadar Road, Shariatpur Sadar',
    details: 'Superintendent of Police Office Help Desk',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'p2',
    name: 'Shariatpur Sadar Police Station (Thana)',
    category: 'police',
    phoneNumber: '+8801320108305',
    upazila: 'Sadar',
    location: 'Thana Road, Shariatpur Sadar',
    details: 'Officer-in-Charge (OC) - Sadar Thana',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'p3',
    name: 'Naria Police Station (Thana)',
    category: 'police',
    phoneNumber: '+8801320108310',
    upazila: 'Naria',
    location: 'Thana Complex, Naria',
    details: 'Officer-in-Charge (OC) - Naria',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'p4',
    name: 'Zajira Police Station (Thana)',
    category: 'police',
    phoneNumber: '+8801320108315',
    upazila: 'Zajira',
    location: 'Zajira Thana Para, Zajira',
    details: 'Officer-in-Charge (OC) - Zajira Thana',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'p5',
    name: 'Bhedarganj Police Station (Thana)',
    category: 'police',
    phoneNumber: '+8801320108320',
    upazila: 'Bhedarganj',
    location: 'Bhedarganj Thana Road',
    details: 'Officer-in-Charge (OC) - Bhedarganj',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'p6',
    name: 'Damudya Police Station (Thana)',
    category: 'police',
    phoneNumber: '+8801320108325',
    upazila: 'Damudya',
    location: 'Damudya Sadar, Damudya',
    details: 'Officer-in-Charge (OC) - Damudya',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'p7',
    name: 'Gosairhat Police Station (Thana)',
    category: 'police',
    phoneNumber: '+8801320108330',
    upazila: 'Gosairhat',
    location: 'Gosairhat Sadar, Gosairhat',
    details: 'Officer-in-Charge (OC) - Gosairhat',
    isEmergency: true,
    verified: true,
  },

  // === FIRE SERVICE ===
  {
    id: 'f1',
    name: 'Shariatpur Sadar Fire Station',
    category: 'fire_service',
    phoneNumber: '+8801730002231',
    upazila: 'Sadar',
    location: 'Angaria, Shariatpur Sadar',
    details: 'Emergency Fire & Rescue Helpline 24/7',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'f2',
    name: 'Naria Fire Station',
    category: 'fire_service',
    phoneNumber: '+8801730002235',
    upazila: 'Naria',
    location: 'Mulafat Ganj, Naria',
    details: 'Naria Fire Fighting Control Room',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'f3',
    name: 'Zajira Fire Station',
    category: 'fire_service',
    phoneNumber: '+8801730002239',
    upazila: 'Zajira',
    location: 'Zajira Pouroshova, Zajira',
    details: 'Zajira Fire Station Emergency Hotline',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'f4',
    name: 'Damudya Fire Station',
    category: 'fire_service',
    phoneNumber: '+8801730302251',
    upazila: 'Damudya',
    location: 'Damudya Bazar Road, Damudya',
    details: 'Fire Fighting and Disaster Management Desk',
    isEmergency: true,
    verified: true,
  },

  // === AMBULANCE ===
  {
    id: 'a1',
    name: 'Sadar Hospital Official Ambulance',
    category: 'ambulance',
    phoneNumber: '+8801712214470',
    upazila: 'Sadar',
    location: 'Shariatpur Sadar Hospital Road',
    details: 'Government subsidized ambulance service, 24/7 availability',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'a2',
    name: 'Red Crescent Ambulance Shariatpur',
    category: 'ambulance',
    phoneNumber: '+8801732525150',
    upazila: 'Sadar',
    location: 'Red Crescent Bhaban, Shariatpur Sadar',
    details: 'Voluntary Emergency Patient Transport Service',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'a3',
    name: 'Zajira Health Complex Ambulance',
    category: 'ambulance',
    phoneNumber: '+8801711202456',
    upazila: 'Zajira',
    location: 'Zajira Upazila Health Complex',
    details: 'Emergency Health Complex Ambulance Service',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'a4',
    name: 'Naria Al-Arafah Ambulance Service',
    category: 'ambulance',
    phoneNumber: '+8801822334455',
    upazila: 'Naria',
    location: 'Naria Launchghat Road',
    details: 'Private emergency service, oxygen-equipped',
    isEmergency: false,
    verified: true,
  },

  // === HOSPITALS & DOCTORS ===
  {
    id: 'h1',
    name: 'শরীয়তপুর সদর হাসপাতাল (২৫০ শয্যা বিশিষ্ট)',
    category: 'hospitals',
    phoneNumber: '01714698009',
    upazila: 'Sadar',
    location: 'শরীয়তপুর সদর',
    details: '২৫০ শয্যা বিশিষ্ট সরকারি সদর হাসপাতাল (জরুরি সেবা ২৪ ঘন্টা খোলা)',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'h2',
    name: 'উপজেলা স্বাস্থ্য কমপ্লেক্স, দামুড্যা',
    category: 'hospitals',
    phoneNumber: '01730324606',
    upazila: 'Damudya',
    location: 'দামুড্যা',
    details: 'সরকারি উপজেলা স্বাস্থ্য কমপ্লেক্স (জরুরি সেবা ও বহির্বিভাগ সচল)',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'h3',
    name: 'নড়িয়া উপজেলা স্বাস্থ্য কমপ্লেক্স',
    category: 'hospitals',
    phoneNumber: '01730324604',
    upazila: 'Naria',
    location: 'নড়িয়া',
    details: 'সরকারি উপজেলা স্বাস্থ্য কমপ্লেক্স (জরুরি সেবা ২৪ ঘন্টা সচল)',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'h4',
    name: 'জাজিরা উপজেলা স্বাস্থ্য কমপ্লেক্স',
    category: 'hospitals',
    phoneNumber: '01730324603',
    upazila: 'Zajira',
    location: 'জাজিরা',
    details: 'সরকারি উপজেলা স্বাস্থ্য কমপ্লেক্স (জরুরি সেবা ও এম্বুলেন্স সেবা সচল)',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'h5',
    name: 'ভেদরগঞ্জ উপজেলা স্বাস্থ্য কমপ্লেক্স',
    category: 'hospitals',
    phoneNumber: '01730324605',
    upazila: 'Bhedarganj',
    location: 'ভেদরগঞ্জ',
    details: 'সরকারি উপজেলা স্বাস্থ্য কমপ্লেক্স (জরুরি সেবা ও মাতৃস্বাস্থ্য বিভাগ)',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'h6',
    name: 'গোসাইরহাট উপজেলা স্বাস্থ্য কমপ্লেক্স',
    category: 'hospitals',
    phoneNumber: '01730324607',
    upazila: 'Gosairhat',
    location: 'গোসাইরহাট',
    details: 'সরকারি উপজেলা স্বাস্থ্য কমপ্লেক্স (জরুরি সেবা ও ইনডোর সুবিধা)',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'h7',
    name: 'ফাতেমা মেডিকেল সেন্টার',
    category: 'hospitals',
    phoneNumber: '01707073567',
    upazila: 'Sadar',
    location: 'সদর রোড, শরীয়তপুর',
    details: 'বেসরকারি সাধারণ চিকিৎসা ও ল্যাব টেস্ট সুবিধা',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h8',
    name: 'নুর জেনারেল হসপিটাল',
    category: 'hospitals',
    phoneNumber: '01943727011',
    upazila: 'Sadar',
    location: 'সদর রোড, গার্লস স্কুলের বিপরীতে, শরীয়তপুর',
    details: 'বেসরকারি জেনারেল হসপিটাল ও বিশেষজ্ঞ ডাক্তার কনসালটেশন',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h9',
    name: 'টিউলিপ হসপিটাল',
    category: 'hospitals',
    phoneNumber: '01901167301',
    upazila: 'Sadar',
    location: 'গার্লস স্কুল রোড, শরীয়তপুর',
    details: 'বেসরকারি আধুনিক জেনারেল ও মেটারনিটি কেয়ার',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h10',
    name: 'শরীয়তপুর স্পেশালাইজড হাসপাতাল',
    category: 'hospitals',
    phoneNumber: '01713236782',
    upazila: 'Sadar',
    location: 'পৌরসভা সংলগ্ন, শরীয়তপুর',
    details: 'বেসরকারি স্পেশালাইজড মাল্টিস্পেশালিটি হাসপাতাল ও অপারেশন থিয়েটার',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h11',
    name: 'আল বারাকা হাসপাতাল',
    category: 'hospitals',
    phoneNumber: '01981888801',
    upazila: 'Sadar',
    location: 'শরীয়তপুর সদর',
    details: 'বেসরকারি জেনারেল হাসপাতাল ও ডায়াগনস্টিক সেন্টার',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h12',
    name: 'নিপুন ডায়াগনস্টিক ও ক্লিনিক',
    category: 'hospitals',
    phoneNumber: '01719609185',
    upazila: 'Sadar',
    location: 'শরীয়তপুর সদর',
    details: 'বেসরকারি আধুনিক প্যাথলজি পরীক্ষা ও ক্লিনিক্যাল সেবা',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h13',
    name: 'কেয়ার ৯৮ (Care98)',
    category: 'hospitals',
    phoneNumber: '01922662253',
    upazila: 'Sadar',
    location: 'চৌরঙ্গী, সদর রোড, শরীয়তপুর',
    details: 'ডায়াগনস্টিক ল্যাব অ্যান্ড কনসালটেশন সেন্টার',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h14',
    name: 'ডক্টরস পয়েন্ট ডায়াগনস্টিক অ্যান্ড কনসালটেশন সেন্টার',
    category: 'hospitals',
    phoneNumber: '01314658000',
    upazila: 'Sadar',
    location: 'সদর হাসপাতাল গেইট, শরীয়তপুর',
    details: 'প্যাথলজি পরীক্ষা, আল্ট্রাসোনোগ্রাফি ও স্পেশালিস্ট ওপিডি',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h15',
    name: 'সিটি আধুনিক হসপিটাল অ্যান্ড ডায়াগনষ্টিিক সেন্টার',
    category: 'hospitals',
    phoneNumber: '01715146899',
    upazila: 'Sadar',
    location: 'চৌরঙ্গী, শরীয়তপুর সদর',
    details: 'আধুনিক হাসপাতাল, মেটারনিটি ওয়ার্ড ও ডিজিটাল ডায়াগনস্টিকস',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h16',
    name: 'রূপসী বাংলা হসপিটাল অ্যান্ড ডায়াগনষ্টিিক সেন্টার',
    category: 'hospitals',
    phoneNumber: '01933154069',
    upazila: 'Sadar',
    location: 'জিরো পয়েন্ট, শরীয়তপুর সদর',
    details: 'বেসরকারি হসপিটাল ও নির্ভরযোগ্য ল্যাব টেস্ট সেবা',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h17',
    name: 'শরীয়তপুর সেন্ট্রাল হাসপাতাল',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Sadar',
    location: 'সদর হাসপাতাল রোড, শরীয়তপুর',
    details: 'বেসরকারি হাসপাতাল (নম্বর পরিবর্তনশীল হওয়ায় সরাসরি যোগাযোগের পরামর্শ)',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h18',
    name: 'শরীয়তপুর দিঘল ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Sadar',
    location: 'শরীয়তপুর সদর',
    details: 'প্যাথলজিক্যাল রক্ত ও হরমোন টেস্ট ডায়াগনস্টিক ল্যাব',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h19',
    name: 'মাজেদা হাসপাতাল ও ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Sadar',
    location: 'শরীয়তপুর সদর',
    details: 'মেডিকেল কেয়ার ও পরীক্ষা কেন্দ্র',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h20',
    name: 'মেডিনোভা ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Sadar',
    location: 'শরীয়তপুর সদর',
    details: 'ডিজিটাল ইমেজিং, এক্সরে ও বায়োকেমিস্ট্রি টেস্ট সেন্টার',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h21',
    name: 'সেবা ক্লিনিক অ্যান্ড ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Damudya',
    location: 'দামুড্যা বাজার, দামুড্যা',
    details: 'দামুড্যা উপজেলার বেসরকারি ক্লিনিক ও প্যাথলজি সেবা',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h22',
    name: 'নিউ মর্ডান ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Damudya',
    location: 'দামুড্যা',
    details: 'আধুনিক ডায়াগনস্টিক ও ল্যাবরেটরি টেস্ট সেন্টার',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h23',
    name: 'মদিনা ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Damudya',
    location: 'দামুড্যা বাজার রোড',
    details: 'জরুরি ক্লিনিক্যাল ল্যাব ও প্যাথলজি',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h24',
    name: 'গ্রীন লাইফ ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Damudya',
    location: 'দামুড্যা',
    details: 'বেসরকারি রক্ত পরীক্ষা ও ডায়াগনস্টিক সেবা',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h25',
    name: 'ডক্টরস কেয়ার ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Damudya',
    location: 'দামুড্যা বাসস্ট্যান্ড সংলগ্ন',
    details: 'কনসালটেশন ও নির্ভরযোগ্য ডায়াগনস্টিক সেন্টার',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h26',
    name: 'জমজম ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Damudya',
    location: 'দামুড্যা বাজার',
    details: 'প্যাথলজি, ইসিজি ও আল্ট্রাসোনোগ্রাফি সেন্টার',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h27',
    name: 'ডিজিটাল ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Damudya',
    location: 'দামুড্যা বাসস্ট্যান্ড এলাকা',
    details: 'ডিজিটাল প্যাথলজি ও হরমোন টেস্ট সেন্টার',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h28',
    name: 'মা ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: 'সরাসরি যোগাযোগ',
    upazila: 'Damudya',
    location: 'উপজেলা গেট সংলগ্ন, দামুড্যা',
    details: 'মা ও শিশু পরীক্ষা এবং প্যাথলজিক্যাল টেস্ট',
    isEmergency: false,
    verified: false,
  },
  {
    id: 'h29',
    name: 'মা ও শিশু ডায়াবেটিক হাসপাতাল',
    category: 'hospitals',
    phoneNumber: '01716618580',
    upazila: 'Naria',
    location: 'ঘড়িষার বাজার, নড়িয়া',
    details: 'মা ও শিশু সাধারণ স্বাস্থ্য সেবা এবং ডায়াবেটিক স্পেশালিস্ট কেয়ার',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h30',
    name: 'ডক্টরস মেডিকেল কেয়ার অ্যান্ড ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: '01333782666',
    upazila: 'Zajira',
    location: 'কাজিরহাট বাসস্ট্যান্ড, জাজিরা',
    details: 'বেসরকারি আধুনিক জেনারেল চিকিৎসা ও ডিজিটাল ডায়াগনস্টিক সেন্টার',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h31',
    name: 'ভেদরগঞ্জ পপুলার ডায়াগনস্টিক অ্যান্ড হসপিটাল',
    category: 'hospitals',
    phoneNumber: '01754761613',
    upazila: 'Bhedarganj',
    location: 'ভেদরগঞ্জ',
    details: 'বেসরকারি ওপিডি ও ডিজিটাল ডায়াগনস্টিক ল্যাব',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'h32',
    name: 'নিউ পপুলার ডায়াগনস্টিক সেন্টার',
    category: 'hospitals',
    phoneNumber: '01788760882',
    upazila: 'Bhedarganj',
    location: 'ভেদরগঞ্জ',
    details: 'মেডিকেল প্যাথলজি ও পরীক্ষা কেন্দ্র',
    isEmergency: false,
    verified: true,
  },

  // === BLOOD DONORS ===
  {
    id: 'b1',
    name: 'Shariatpur Blood Bank Volunteer Network',
    category: 'blood_donors',
    phoneNumber: '+8801711223399',
    upazila: 'Sadar',
    location: 'Sadar Hospital Road, Shariatpur',
    details: 'Network of 200+ volunteers. Contact for all groups: A+, B+, O+, AB+',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'b2',
    name: 'Zajira Rokto Seba Association',
    category: 'blood_donors',
    phoneNumber: '+8801822334411',
    upazila: 'Zajira',
    location: 'Zajira Bazar, Zajira',
    details: 'Voluntary blood donors organization specializing in Zajira area.',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'b3',
    name: 'Naria Blood Donors Club',
    category: 'blood_donors',
    phoneNumber: '+8801911445566',
    upazila: 'Naria',
    location: 'Naria Municipality, Naria',
    details: 'Quick response team for urgent blood needs (O+ and B+ priority).',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'b4',
    name: 'Kazi Arif (O+ Donor Volunteer)',
    category: 'blood_donors',
    phoneNumber: '+8801755123456',
    upazila: 'Bhedarganj',
    location: 'Bhedarganj Bazar',
    details: 'Blood Group: O Positive. Ready for emergency donations.',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'b5',
    name: 'Siddique Rahman (A- rare blood group)',
    category: 'blood_donors',
    phoneNumber: '+8801688112233',
    upazila: 'Gosairhat',
    location: 'Gosairhat Pouroshova',
    details: 'Blood Group: A Negative (Rare Group). Emergency volunteer.',
    isEmergency: true,
    verified: true,
  },

  // === PHARMACIES ===
  {
    id: 'ph1',
    name: 'Sadar Model Pharmacy (24 Hours)',
    category: 'pharmacies',
    phoneNumber: '+8801711123456',
    upazila: 'Sadar',
    location: 'Hospital Main Gate, Shariatpur Sadar',
    details: 'Life-saving medicines available 24/7. Home delivery inside Sadar.',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'ph2',
    name: 'Lazz Pharma Franchise - Shariatpur',
    category: 'pharmacies',
    phoneNumber: '+8801733221100',
    upazila: 'Sadar',
    location: 'Court Road, Shariatpur Sadar',
    details: 'Reliable medicine shop, opens 7:00 AM to Midnight.',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'ph3',
    name: 'Zajira Drug House (Emergency Night Service)',
    category: 'pharmacies',
    phoneNumber: '+8801815667788',
    upazila: 'Zajira',
    location: 'Zajira Upazila Health Complex Road',
    details: '24/7 emergency medicine supply near health complex.',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'ph4',
    name: 'Janani Pharmacy Naria',
    category: 'pharmacies',
    phoneNumber: '+8801912554433',
    upazila: 'Naria',
    location: 'Mulafat Ganj Bazar, Naria',
    details: 'All types of local and imported medicines. Regular stock.',
    isEmergency: false,
    verified: true,
  },

  // === TRANSPORTATION ===
  {
    id: 't1',
    name: 'Shariatpur Chayanil Transport Counter (Sadar)',
    category: 'transportation',
    phoneNumber: '+8801711559988',
    upazila: 'Sadar',
    location: 'Angaria Bus Stand, Shariatpur Sadar',
    details: 'Direct Bus Service Shariatpur to Dhaka (via Padma Bridge). Schedule: 5 AM - 8 PM',
    isEmergency: false,
    verified: true,
  },
  {
    id: 't2',
    name: 'Shariatpur Padma Travels Counter',
    category: 'transportation',
    phoneNumber: '+8801811554433',
    upazila: 'Zajira',
    location: 'Zajira Bus Stand, Zajira',
    details: 'AC and Non-AC coaches. Zajira to Dhaka via Padma Bridge.',
    isEmergency: false,
    verified: true,
  },
  {
    id: 't3',
    name: 'Naria Launch Terminal Counter (Naria to Dhaka)',
    category: 'transportation',
    phoneNumber: '+8801712445588',
    upazila: 'Naria',
    location: 'Naria Launch Ghat, Naria',
    details: 'Daily luxury launch departures to Dhaka Sadarghat. Launch departures at 10:00 PM.',
    isEmergency: false,
    verified: true,
  },
  {
    id: 't4',
    name: 'Sadar Emergency Rent-a-Car Association',
    category: 'transportation',
    phoneNumber: '+8801715668822',
    upazila: 'Sadar',
    location: 'Central Shaheed Minar Road, Sadar',
    details: 'Rent-a-car, Microbus, and Ambulance rent 24/7 for medical emergencies.',
    isEmergency: true,
    verified: true,
  },

  // === GOVERNMENT OFFICES ===
  {
    id: 'g1',
    name: 'Shariatpur Palli Bidyut Samity Head Office',
    category: 'gov_offices',
    phoneNumber: '+8801769400100',
    upazila: 'Sadar',
    location: 'Palli Bidyut Road, Shariatpur Sadar',
    details: 'Electricity Complaints, Emergency Outage Hotline & Support.',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'g2',
    name: 'Palli Bidyut Sub-office Damudya',
    category: 'gov_offices',
    phoneNumber: '+8801769400108',
    upazila: 'Damudya',
    location: 'Damudya Sub-office',
    details: 'Local power complaints & repair services.',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'g3',
    name: 'Deputy Commissioner (DC) Office Shariatpur',
    category: 'gov_offices',
    phoneNumber: '+8802478815100',
    upazila: 'Sadar',
    location: 'Collectorate Building, Shariatpur Sadar',
    details: 'District Administration Desk, General Public Affairs & Inquiries.',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'g4',
    name: 'Zajira Municipality Office (Pouroshova)',
    category: 'gov_offices',
    phoneNumber: '+8801711229988',
    upazila: 'Zajira',
    location: 'Zajira Pouro Bhaban, Zajira',
    details: 'Public utility services, birth registration help desk, civic services.',
    isEmergency: false,
    verified: true,
  },

  // === EMERGENCY MECHANICS ===
  {
    id: 'm1',
    name: 'Milon Motorcycle Repairing & Towing Garage',
    category: 'mechanics',
    phoneNumber: '+8801712456789',
    upazila: 'Sadar',
    location: 'Angaria Bypass Road, Shariatpur Sadar',
    details: 'Emergency bike towing and repairs. Open late (until 11:00 PM).',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'm2',
    name: 'Zajira Auto-Rickshaw & Car Mechanics',
    category: 'mechanics',
    phoneNumber: '+8801911442233',
    upazila: 'Zajira',
    location: 'Majhirghat Highway Road, Zajira',
    details: 'CNG, Auto, and Microbus repair. Specialized in highway breakdowns.',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'm3',
    name: 'Naria Outboard Boat Engine & Motor Mechanic',
    category: 'mechanics',
    phoneNumber: '+8801822338877',
    upazila: 'Naria',
    location: 'Launch Ghat Road, Naria',
    details: 'Specialist in speedboat and boat engines. Emergency river assistance.',
    isEmergency: false,
    verified: true,
  },

  // === NATIONAL EMERGENCY HOTLINES ===
  {
    id: 'htl1',
    name: 'জাতীয় জরুরি সেবা (National Emergency Service)',
    category: 'hotlines',
    phoneNumber: '999',
    upazila: 'Sadar',
    location: 'সারাদেশে ২৪/৭ বিনামূল্যে (Toll Free)',
    details: 'পুলিশ, ফায়ার সার্ভিস ও অ্যাম্বুলেন্স জরুরি কলের জন্য টোল-ফ্রি হেল্পলাইন।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'htl2',
    name: 'সরকারি তথ্য ও সেবা (National Help Desk)',
    category: 'hotlines',
    phoneNumber: '333',
    upazila: 'Sadar',
    location: 'জাতীয় কল সেন্টার ৩৩৩',
    details: 'সরকারি সেবা, দুর্যোগ সম্পর্কিত তথ্য ও সামাজিক সমস্যা সংক্রান্ত জরুরি হেল্পলাইন।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'htl3',
    name: 'নারী ও শিশু নির্যাতন প্রতিরোধ সেল',
    category: 'hotlines',
    phoneNumber: '109',
    upazila: 'Sadar',
    location: 'মহিলা ও শিশু বিষয়ক মন্ত্রণালয়',
    details: 'নারী ও শিশুদের বিরুদ্ধে সহিংসতা প্রতিরোধে ২৪ ঘণ্টা টোল-ফ্রি হটলাইন।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'htl4',
    name: 'শিশু সহায়তা হটলাইন (Child Helpline)',
    category: 'hotlines',
    phoneNumber: '1098',
    upazila: 'Sadar',
    location: 'সমাজসেবা অধিদপ্তর',
    details: 'ঝুঁকিপূর্ণ শিশুদের সার্বিক জরুরি সুরক্ষা সহায়তার জন্য।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'htl5',
    name: 'স্বাস্থ্য বাতায়ন (Health Call Center)',
    category: 'hotlines',
    phoneNumber: '16263',
    upazila: 'Sadar',
    location: 'স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়',
    details: '২৪ ঘণ্টা অভিজ্ঞ ডাক্তারের বিনামূল্যে চিকিৎসা পরামর্শ ও অ্যাম্বুলেন্স তথ্য।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'htl6',
    name: 'দুর্যোগের আগাম বার্তা হটলাইন',
    category: 'hotlines',
    phoneNumber: '1090',
    upazila: 'Sadar',
    location: 'দুর্যোগ ব্যবস্থাপনা অধিদপ্তর',
    details: 'বন্যা, ঝড় ও নদী ভাঙন সম্পর্কিত আবহাওয়া সতর্কবার্তা হেল্পলাইন।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'htl7',
    name: 'ভূমি সেবা হটলাইন (Land Services)',
    category: 'hotlines',
    phoneNumber: '16122',
    upazila: 'Sadar',
    location: 'ভূমি মন্ত্রণালয়, গণপ্রজাতন্ত্রী বাংলাদেশ সরকার',
    details: 'নামজারি, খতিয়ান, ই-পর্চা, ভূ-উন্নয়ন কর ও ই-নামজারি সমাধান।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'htl8',
    name: 'দুদক অভিযোগ হটলাইন (ACC Hotline)',
    category: 'hotlines',
    phoneNumber: '106',
    upazila: 'Sadar',
    location: 'দুর্নীতি দমন কমিশন (দুদক)',
    details: 'সরকারি ও আধা-সরকারি প্রতিষ্ঠানে ঘুষ ও দুর্নীতির অভিযোগ গ্রহণের জরুরি নম্বর।',
    isEmergency: true,
    verified: true,
  },

  // === EDUCATION & COLLEGES ===
  {
    id: 'edu1',
    name: 'শরীয়তপুর সরকারি কলেজ',
    category: 'education',
    phoneNumber: '+8802478815234',
    upazila: 'Sadar',
    location: 'কলেজ রোড, শরীয়তপুর সদর',
    details: 'প্রধান প্রশাসনিক দপ্তর, অনার্স ও মাস্টার্স ভর্তি সহায়তা কেন্দ্র।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'edu2',
    name: 'শরীয়তপুর পলিটেকনিক ইনস্টিটিউট',
    category: 'education',
    phoneNumber: '+8801711998877',
    upazila: 'Naria',
    location: 'বুড়িরহাট, নড়িয়া, শরীয়তপুর',
    details: 'ডিপ্লোমা ইন ইঞ্জিনিয়ারিং শাখা কার্যালয় ও ইনফরমেশন ডেক্স।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'edu3',
    name: 'জাজিরা সরকারি কলেজ',
    category: 'education',
    phoneNumber: '+8801819887766',
    upazila: 'Zajira',
    location: 'কলেজ মোড়, জাজিরা',
    details: 'ডিগ্রি ও একাদশ শ্রেণির ভর্তি এবং তথ্য কেন্দ্র।',
    isEmergency: false,
    verified: true,
  },

  // === BANKS & ATMS ===
  {
    id: 'bnk1',
    name: 'সোনালী ব্যাংক শরীয়তপুর প্রধান শাখা',
    category: 'banks',
    phoneNumber: '+8802478815120',
    upazila: 'Sadar',
    location: 'কোর্ট রোড, শরীয়তপুর সদর',
    details: 'সরকারি চালান, পেনশন, ডিপোজিট ও ২৪ ঘণ্টা এটিএম সার্ভিস।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'bnk2',
    name: 'ইসলামী ব্যাংক শরীয়তপুর শাখা',
    category: 'banks',
    phoneNumber: '+8801711443322',
    upazila: 'Sadar',
    location: 'সদর হাসপাতাল মোড়, শরীয়তপুর',
    details: 'বৈদেশিক রেমিট্যান্স, ডাচ-বাংলা রকেট ও এটিএম সুবিধা।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'bnk3',
    name: 'ডাচ-বাংলা ব্যাংক ফাস্ট ট্র্যাক & ATM (জাজিরা)',
    category: 'banks',
    phoneNumber: '+8801911002288',
    upazila: 'Zajira',
    location: 'জাজিরা বাজার পয়েন্ট, জাজিরা',
    details: '২৪/৭ ক্যাশ আউট ও বিকাশ/রকেট/নগদ এজেন্ট পয়েন্ট।',
    isEmergency: false,
    verified: true,
  },

  // === LEGAL AID & LAWYERS ===
  {
    id: 'lgl1',
    name: 'শরীয়তপুর জেলা জজ কোর্ট লিগ্যাল এইড অফিসার',
    category: 'legal_help',
    phoneNumber: '+8801700705599',
    upazila: 'Sadar',
    location: 'জেলা জজ আদালত ভবন, শরীয়তপুর',
    details: 'দরিদ্র ও অসহায়দের সরকারি খরচে বিনামূল্যে আইনি সহায়তা।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'lgl2',
    name: 'শরীয়তপুর জেলা আইনজীবী সমিতি (Bar Association)',
    category: 'legal_help',
    phoneNumber: '+8802478815330',
    upazila: 'Sadar',
    location: 'বার অ্যাসোসিয়েশন ভবন, কোর্ট রোড',
    details: 'আইনজীবী ও নোটারি পাবলিক তথ্য ডেস্ক।',
    isEmergency: false,
    verified: true,
  },

  // === JOURNALISTS & PRESS CLUB ===
  {
    id: 'jrn1',
    name: 'শরীয়তপুর প্রেস ক্লাব (Shariatpur Press Club)',
    category: 'journalists',
    phoneNumber: '+8801712998811',
    upazila: 'Sadar',
    location: 'ধনুকা মোড়, শরীয়তপুর সদর',
    details: 'জেলা সাংবাদিক সমিতি ও জাতীয় দৈনিক/টিভি রিপোর্টার্স হেল্প ডেস্ক।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'jrn2',
    name: 'নড়িয়া উপজেলা প্রেস ক্লাব',
    category: 'journalists',
    phoneNumber: '+8801811334455',
    upazila: 'Naria',
    location: 'পৌরসভা রোড, নড়িয়া',
    details: 'স্থানীয় সংবাদ প্রতিনিধি ও মিডিয়া যোগাযোগ।',
    isEmergency: false,
    verified: true,
  },

  // === HOTELS & TOURISM ===
  {
    id: 'htl_t1',
    name: 'শরীয়তপুর জেলা সার্কিট হাউজ (Circuit House)',
    category: 'hotels_tourism',
    phoneNumber: '+8802478815105',
    upazila: 'Sadar',
    location: 'সার্কিট হাউজ রোড, শরীয়তপুর',
    details: 'সরকারি কর্মকর্তা ও অনুমোদিত অতিথিদের আবাসন ব্যবস্থা।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'htl_t2',
    name: 'পদ্মা সেতু জাজিরা রিসোর্ট & রেস্ট হাউস',
    category: 'hotels_tourism',
    phoneNumber: '+8801711223344',
    upazila: 'Zajira',
    location: 'পদ্মা সেতু টোল প্লাজা সংলগ্ন, জাজিরা',
    details: 'পদ্মা সেতু দর্শনার্থীদের জন্য আবাসন, গাড়ি পার্কিং ও রেস্টুরেন্ট।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'htl_t3',
    name: 'হোটেল স্বর্ণা (Hotel Swarna & Residential)',
    category: 'hotels_tourism',
    phoneNumber: '+8801912556677',
    upazila: 'Sadar',
    location: 'সদর বাসস্ট্যান্ড মোড়, শরীয়তপুর',
    details: 'এসি ও নন-এসি রুমের আবাসিক হোটেল।',
    isEmergency: false,
    verified: true,
  },

  // === AGRICULTURE & LIVESTOCK ===
  {
    id: 'agr1',
    name: 'উপজেলা কৃষি সম্প্রসারণ কার্যালয় (শরীয়তপুর সদর)',
    category: 'agriculture',
    phoneNumber: '+8801711229988',
    upazila: 'Sadar',
    location: 'কৃষি ভবন, কোর্ট রোড, শরীয়তপুর সদর',
    details: 'ফসল রক্ষা, সার-বীজ পরামর্শ ও বিনামূল্যে কৃষি অফিসারদের স্বাস্থ্য পরামর্শ।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'agr2',
    name: 'জেলা প্রাণিসম্পদ হাসপাতাল ও ভেটেরিনারি ক্লিনিক',
    category: 'agriculture',
    phoneNumber: '+8802478815199',
    upazila: 'Sadar',
    location: 'হাসপাতাল রোড, শরীয়তপুর',
    details: 'গবাদিপশু ও হাঁস-মুরগির চিকিৎসা, ভ্যাকসিনেশন ও জরুরি ভেটেরিনারি সার্জন।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'agr3',
    name: 'নড়িয়া উপজেলা মৎস্য অফিস (Fisheries Office)',
    category: 'agriculture',
    phoneNumber: '+8801819334411',
    upazila: 'Naria',
    location: 'উপজেলা কমপ্লেক্স, নড়িয়া',
    details: 'পোনা মাছ চাষ, ইলিশ সংরক্ষণ ও মৎস্যচাষীদের সরকারি সহায়তা ডেস্ক।',
    isEmergency: false,
    verified: true,
  },

  // === UNION & DIGITAL CENTERS ===
  {
    id: 'udc1',
    name: 'শরীয়তপুর সদর ইউনিয়ন পরিষদ ও ডিজিটাল সেন্টার',
    category: 'union_parishad',
    phoneNumber: '+8801715882233',
    upazila: 'Sadar',
    location: 'পৌরসভা ভবন সংলগ্ন, শরীয়তপুর',
    details: 'জন্ম-মৃত্যু নিবন্ধন, নাগরিক সনদ, ওয়ারিশ সনদ ও অনলাইন সেবা।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'udc2',
    name: 'জাজিরা ইউনিয়ন ডিজিটাল সেন্টার (UDC)',
    category: 'union_parishad',
    phoneNumber: '+8801913778899',
    upazila: 'Zajira',
    location: 'জাজিরা বাজার পয়েন্ট',
    details: 'অনলাইন এনআইডি সংশোধন, খতিয়ান বা পরচা আবেদন ও উদ্যোক্তা নম্বর।',
    isEmergency: false,
    verified: true,
  },

  // === PASSPORT, NID & LAND SERVICES ===
  {
    id: 'pass1',
    name: 'শরীয়তপুর আঞ্চলিক পাসপোর্ট অফিস (Passport Office)',
    category: 'passport_land',
    phoneNumber: '+8802478815100',
    upazila: 'Sadar',
    location: 'ধনুকা, শরীয়তপুর সদর',
    details: 'ই-পাসপোর্ট আবেদন, ডেলিভারি স্ট্যাটাস অনুসন্ধান ও হেল্পডেস্ক।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'pass2',
    name: 'উপজেলা সহকারী কমিশনার (ভূমি) / AC Land Office',
    category: 'passport_land',
    phoneNumber: '+8801700712233',
    upazila: 'Sadar',
    location: 'ভূমি অফিস রোড, শরীয়তপুর সদর',
    details: 'ই-নামজারি (Mutation), ভূমি উন্নয়ন কর ও জমি রেজিস্ট্রেশন সংক্রান্ত তথ্য।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'pass3',
    name: 'জেলা নির্বাচন অফিস (NID Help Desk)',
    category: 'passport_land',
    phoneNumber: '+8801711009988',
    upazila: 'Sadar',
    location: 'কালেক্টরেট ভবন, শরীয়তপুর',
    details: 'নতুন ভোটার হওয়া, এনআইডি কার্ড সংশোধন ও স্মার্ট কার্ড বিতরণ ডেস্ক।',
    isEmergency: false,
    verified: true,
  },

  // === HOME NURSING & OXYGEN ===
  {
    id: 'nrse1',
    name: 'শরীয়তপুর হোম কেয়ার নার্সিং & ফিজিওথেরাপি',
    category: 'home_nursing',
    phoneNumber: '+8801712334455',
    upazila: 'Sadar',
    location: 'সদর হাসপাতাল গেট সংলগ্ন',
    details: 'বাসায় গিয়ে প্রবীণ রোগী দেখাশোনা, ড্রেসিং, সেলাইন ও ফিজিওথেরাপি দেওয়া।',
    isEmergency: true,
    verified: true,
  },
  {
    id: 'nrse2',
    name: 'জরুরি অক্সিজেন সিলিন্ডার ব্যাংক (Shariatpur Oxygen)',
    category: 'home_nursing',
    phoneNumber: '+8801811990022',
    upazila: 'Sadar',
    location: 'ধনুকা, শরীয়তপুর',
    details: '২৪/৭ হোম ডেলিভারিসহ মেডিকেল গ্রেড অক্সিজেন সিলিন্ডার সরবরাহ ও রিফিল।',
    isEmergency: true,
    verified: true,
  },

  // === COURIER & PARCEL SERVICES ===
  {
    id: 'cur1',
    name: 'সুন্দরবন কুরিয়ার সার্ভিস (শরীয়তপুর সদর শাখা)',
    category: 'courier',
    phoneNumber: '+8801711883322',
    upazila: 'Sadar',
    location: 'পালং বাজার মোড়, শরীয়তপুর',
    details: 'পার্সেল বুকিং, ক্যাশ অন ডেলিভারি (COD) ও হোম ডেলিভারি।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'cur2',
    name: 'এস. এ. পরিবহন লিমিটেড (S.A. Paribahan)',
    category: 'courier',
    phoneNumber: '+8801911445566',
    upazila: 'Sadar',
    location: 'কোর্ট রোড, শরীয়তপুর',
    details: 'জরুরি ডক প্রসেসিং, টাকা ট্রান্সফার ও ভারী মালামাল পরিবহন।',
    isEmergency: false,
    verified: true,
  },
  {
    id: 'cur3',
    name: 'স্টিডফাস্ট & রেডএক্স কুরিয়ার হাব (Steadfast Courier)',
    category: 'courier',
    phoneNumber: '+8801812990011',
    upazila: 'Sadar',
    location: 'মনোরম মোড়, শরীয়তপুর',
    details: 'অনলাইন ই-কমার্স শপ মার্চেন্ট ও সাধারণ গ্রাহকদের পার্সেল বুকিং।',
    isEmergency: false,
    verified: true,
  }
];
